### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by Alimjan2013** [James-Leste/GApe#14]
# question: 
can't register or login 
# how:
when i using register page, i can input but when i press button, it's popup dialog "Invalid credentials"
<img width="872" alt="image" src="https://github.com/user-attachments/assets/7e770ddd-12fd-4f45-a651-2f9232976a2e">

**Comment by James-Leste** [comment]
Authentication logics will be implemented in branch [feature/login](https://github.com/James-Leste/GApe/tree/feature/login). This branch is only for ui implementation.

**Comment by Alimjan2013** [comment]
got it ! thank you for clarification, i can close this issue now.
